#!/bin/bash

#copy tests from cae space (must have permission to do so)

if [ ! -f mw_test_files.tar.gz ]; then
scp cae:/userspace/c/cnerg/cnerg/users/shriwise/mw_test_files.tar.gz ./.
fi

tar xzvf mw_test_files.tar.gz

make clean

make 

echo "RUNNING TEST_CYL..."
./test_cyl

make test_iter

echo "RUNNING TEST_ITER..."
./test_iter 

make test_fnsf_360

echo "RUNNING TEST_FNSF..."
./test_fnsf_360

make test_bllite

echo "RUNNING TEST_BLLITE..."
./test_bllite
